# Generated by Django 3.2.17 on 2023-02-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.genre')),
            ],
        ),
    ]
