# Generated by Django 3.2.17 on 2023-02-14 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgenre',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_genres', to='events.event'),
        ),
    ]
