# Generated by Django 3.2.17 on 2023-02-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_gallery_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('title', 'date', 'location')},
        ),
    ]
