# Generated by Django 3.2.17 on 2023-02-22 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_gallery_name'),
        ('comments', '0001_initial'),
        ('buttons', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='going',
            name='posted_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goings', to='events.event'),
        ),
        migrations.AlterField(
            model_name='interested',
            name='posted_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesteds', to='events.event'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment'),
        ),
    ]
